# 1. LA CONEXIÓN A AZURE
spring.datasource.url=jdbc:postgresql://finanzas-juanf.postgres.database.azure.com:5432/postgres
spring.datasource.username=adminjuan
spring.datasource.password=72200571@Jf

# 2. EL DIALECTO PARA POSTGRESQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=9090

# 3. ACTUALIZACIÓN AUTOMÁTICA DE TABLAS (La magia de Hibernate)
spring.jpa.hibernate.ddl-auto=update

# MOSTRAR EL SQL EN CONSOLA PARA VERIFICAR LA CONEXIÓN
spring.jpa.show-sql=true

# Configuración de Correo (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=product.maxima.23@gmail.com
spring.mail.password=gzbk ajsq evjm woop
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true