-- Baseline schema for the financial tracker (Fases 2-3).
-- Authored to run on both H2 (MODE=PostgreSQL, dev/test) and PostgreSQL (prod).
-- Identity columns use the ANSI "generated by default as identity" form, supported
-- by H2 and PostgreSQL 10+. Enum columns are plain VARCHAR; the application layer
-- enforces the allowed values (see hibernate.type.preferred_enum_jdbc_type=VARCHAR).

CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    nombre VARCHAR(255),
    fecha_registro TIMESTAMP(6),
    codigo_otp VARCHAR(4),
    expiracion_otp TIMESTAMP(6),
    intentos_otp INTEGER DEFAULT 0 NOT NULL,
    tipo_negocio VARCHAR(255)
);

CREATE TABLE categorias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    tipo VARCHAR(255) NOT NULL,
    usuario_id BIGINT,
    CONSTRAINT fk_categorias_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
);

CREATE TABLE transacciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    monto NUMERIC(38, 2) NOT NULL,
    tipo VARCHAR(255) NOT NULL,
    descripcion VARCHAR(500),
    fecha TIMESTAMP(6) NOT NULL,
    categoria_id BIGINT,
    usuario_id BIGINT NOT NULL,
    CONSTRAINT fk_transacciones_categoria FOREIGN KEY (categoria_id) REFERENCES categorias (id),
    CONSTRAINT fk_transacciones_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
);

CREATE TABLE metas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    monto_objetivo NUMERIC(38, 2) NOT NULL,
    periodo VARCHAR(7) NOT NULL,
    activa BOOLEAN NOT NULL,
    dias_laborables VARCHAR(20),
    CONSTRAINT fk_metas_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
);
