-- Refresh tokens for short-lived access JWT renewal (Fase 5.4 / #14).
-- Only the SHA-256 hash of the raw token is stored. Portable across H2 and PostgreSQL.

CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    usuario_id BIGINT NOT NULL,
    expiracion TIMESTAMP(6) NOT NULL,
    revocado BOOLEAN NOT NULL,
    CONSTRAINT fk_refresh_tokens_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
);
