-- Monthly per-category spending budgets (Analytics roadmap #3).
-- One budget per (usuario, categoria): the UNIQUE constraint backs the upsert.
-- montoMensual is a fixed cap; the current-month spend is computed on read from
-- transacciones, so there is no per-month budget history.
-- Portable across H2 (MODE=PostgreSQL) and PostgreSQL.

CREATE TABLE presupuestos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    categoria_id BIGINT NOT NULL,
    monto_mensual NUMERIC(38, 2) NOT NULL,
    CONSTRAINT fk_presupuestos_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id),
    CONSTRAINT fk_presupuestos_categoria FOREIGN KEY (categoria_id) REFERENCES categorias (id),
    CONSTRAINT uq_presupuestos_usuario_categoria UNIQUE (usuario_id, categoria_id)
);
